version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webhook-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11x5mf5f3ylgv"
s3_prefix = "webhook-function"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
confirm_changeset = false
